# -*- coding: utf-8 -*-
"""landsat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsHNDFpkOica8Evof_OUwm3dmZtpxp5R
"""

import geemap,geemap as import_map

import ee

ee.Authenticate()
ee.Initialize(project='ee-mushkaan2024')
Map=import_map.Map()

studyarea=ee.FeatureCollection('projects/ee-mushkaan2024/assets/new_delhi')

landsat7_data = ee.ImageCollection("LANDSAT/LE07/C02/T1").filterDate('2000-06-01', '2000-12-31')
landsat9_data = ee.ImageCollection("LANDSAT/LC09/C02/T1").filterDate('2024-06-01', '2024-12-31')

landsat7_fcc_2000=landsat7_data.select('B4','B3','B2').mean().clip(studyarea)
landsat7_tcc_2000=landsat7_data.select('B3','B2','B1').mean().clip(studyarea)
Map.addLayer(landsat7_fcc_2000,{},'FCC_2000')
Map.addLayer(landsat7_tcc_2000,{},'TCC_2000') #adding TCC and FCC datasets of Landsat 7 for the year of 2000

landsat9_fcc_2024=landsat9_data.select('B5','B4','B3').mean().clip(studyarea)
landsat9_tcc_2024=landsat9_data.select('B4','B3','B2').mean().clip(studyarea)
Map.addLayer(landsat9_fcc_2024,{},'FCC_2024')
Map.addLayer(landsat9_tcc_2024,{},'TCC_2024') #adding TCC and FCC datasets of Landsat 9 for the year of 2024

Map



