# -*- coding: utf-8 -*-
"""residential_delhi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1wkqZ9TzoASofxZ_mAp5XtDCFDUypSA
"""

import geemap,geemap as import_map

import ee

ee.Authenticate()
ee.Initialize(project='ee-mushkaan2024')
map=import_map.Map()

vector_layer = ee.FeatureCollection("projects/ee-mushkaan2024/assets/residential")

Map = geemap.Map()

Map.addLayer(vector_layer, {}, 'residential New Delhi')

Map