# -*- coding: utf-8 -*-
"""Sentinel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTzmyNUvbIoqbS2n6T4MVQ0x0d0e3LX2
"""

import geemap,geemap as import_map

import ee

ee.Authenticate()
ee.Initialize(project='ee-mushkaan2024')
Map=import_map.Map()

study_area=ee.FeatureCollection('projects/ee-mushkaan2024/assets/new_delhi') #defining my study area

sentinel_data_2016=ee.ImageCollection("COPERNICUS/S2_HARMONIZED").filterDate('2016-01-01', '2016-12-31').filterMetadata('CLOUDY_PIXEL_PERCENTAGE','less_than',10)
sentinel_data_2024=ee.ImageCollection("COPERNICUS/S2_HARMONIZED").filterDate('2024-06-01', '2024-12-31').filterMetadata('CLOUDY_PIXEL_PERCENTAGE','less_than',10)

sentinel_2016_tcc=sentinel_data_2016.select('B4','B3','B2').mean().clip(study_area)
sentinel_2016_fcc=sentinel_data_2016.select('B8','B4','B3').mean().clip(study_area)

sentinel_2024_tcc=sentinel_data_2024.select('B4','B3','B2').mean().clip(study_area)
sentinel_2024_fcc=sentinel_data_2024.select('B8','B4','B3').mean().clip(study_area)

sentinel_2024_tcc=sentinel_data_2024.select('B4','B3','B2').mean().clip(study_area)
sentinel_2024_fcc=sentinel_data_2024.select('B8','B4','B3').mean().clip(study_area)

Map.addLayer(sentinel_2016_tcc,{},'TCC_2016')
Map.addLayer(sentinel_2016_fcc,{},'FCC_2016')
Map.addLayer(sentinel_2024_tcc,{},'TCC_2024')
Map.addLayer(sentinel_2024_fcc,{},'FCC_2024')

Map.center_object(study_area,9)
Map



